-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 19:30:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema systemhealth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema systemhealth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `systemhealth` DEFAULT CHARACTER SET utf8 ;
USE `systemhealth` ;

-- -----------------------------------------------------
-- Table `systemhealth`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Usuario` (
  `idUsuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `foto` MEDIUMBLOB NULL,
  `role` VARCHAR(20) NULL,
  `confirmation` INT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemhealth`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `edad` INT NULL,
  `peso` INT NULL,
  `estatura` INT NULL,
  `sexo` VARCHAR(1) NULL,
  `tipoDeSangre` VARCHAR(4) NULL,
  PRIMARY KEY (`idPaciente`),

  CONSTRAINT `idUsuarioPaciente`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `systemhealth`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemhealth`.`Medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Medicamento` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `dosis` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemhealth`.`Cantidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Cantidades` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Cantidades` (
  `idCantidades` INT NOT NULL AUTO_INCREMENT,
  `idMedicamento` INT NULL,
  `cantidad` INT NULL,
  `descripcion` VARCHAR(120) NULL,
  PRIMARY KEY (`idCantidades`),
  CONSTRAINT `idMedicamentoCantidades`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `systemhealth`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemhealth`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Doctor` (
  `idDoctor` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `edad` INT NULL,
  `especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idDoctor`),
  CONSTRAINT `idUsuarioDoctor`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `systemhealth`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemhealth`.`Receta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Receta` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Receta` (
  `idReceta` INT NOT NULL AUTO_INCREMENT,
  `numReceta` INT NULL,
  `idCantidades` INT NULL,
  `idDoctor` INT NULL,
  `idPaciente` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idReceta`),
  CONSTRAINT `idPacienteReceta`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `systemhealth`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCantidadesReceta`
    FOREIGN KEY (`idCantidades`)
    REFERENCES `systemhealth`.`Cantidades` (`idCantidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCantidadeDoctor`
    FOREIGN KEY (`idDoctor`)
    REFERENCES `systemhealth`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemhealth`.`Confirmation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Confirmation` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Confirmation` (
  `idConfirmation` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` VARCHAR(45) NULL,
  `confirmation` INT NULL,
  PRIMARY KEY (`idConfirmation`),
  CONSTRAINT `idUsuarioConfirmation`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `systemhealth`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemhealth`.`Entidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Entidad` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Entidad` (
  `cveEnt` VARCHAR(5) NOT NULL,
  `nomEnt` VARCHAR(50) NULL,
  `nomAbr` VARCHAR(10) NULL,
  PRIMARY KEY (`cveEnt`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `systemhealth`.`Municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Municipio` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `cveEnt` VARCHAR(5) NOT NULL,
  `cveMun` VARCHAR(3) NULL,
  `nomMun` VARCHAR(50) NULL,
  `cveCab` VARCHAR(4) NULL,
  `nomCab` VARCHAR(50) NULL,
  PRIMARY KEY (`idMunicipio`),
  CONSTRAINT `cveEntMunicipio`
    FOREIGN KEY (`cveEnt`)
    REFERENCES `systemhealth`.`Entidad` (`cveEnt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemhealth`.`Consultorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systemhealth`.`Consultorio` ;

CREATE TABLE IF NOT EXISTS `systemhealth`.`Consultorio` (
  `idConsultorio` INT NOT NULL AUTO_INCREMENT,
  `idDoctor` INT NULL,
  `idMunicipio` INT NULL,
  PRIMARY KEY (`idConsultorio`),
  CONSTRAINT `idDoctorConsultorio`
    FOREIGN KEY (`idDoctor`)
    REFERENCES `systemhealth`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEntidadConsultorio`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `systemhealth`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



